# Generated by Django 2.2.7 on 2019-11-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('claveArticulo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencias', models.IntegerField()),
            ],
        ),
    ]
